name: Random GIF in README

on:
  schedule:
    - cron: "0 */6 * * *" # Executa a cada 6 horas
  workflow_dispatch:

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Definir próximo GIF
        run: |
          # Lista de GIFs
          GIFS=("https://media.tenor.com/zZ2o8_ONLRIAAAAj/jojo-fortnite.gif" \
                "https://media.tenor.com/9qvRhTR47joAAAAj/shadow-dio-jjba.gif" \
                "https://media.tenor.com/zVj0tqzt_MAAAC/touhou-sakuya-floss.gif")

          # Lê índice do último commit (ou inicia com 0)
          INDEX_FILE=".github/workflows/last_gif_index.txt"
          if [ -f "$INDEX_FILE" ]; then
            INDEX=$(cat "$INDEX_FILE")
          else
            INDEX=0
          fi

          # Define o GIF atual
          GIF_ESCOLHIDO=${GIFS[$INDEX]}
          echo "GIF_ESCOLHIDO=$GIF_ESCOLHIDO" >> $GITHUB_ENV

          # Próximo índice
          NEXT_INDEX=$(( (INDEX + 1) % ${#GIFS[@]} ))
          echo "$NEXT_INDEX" > "$INDEX_FILE"

      - name: Atualizar README
        run: |
          sed -i "s|<img src=\"https://media\.tenor\.com/[^\"]*\" height=\"160\" style=\"margin-bottom: 10px;\" />|<img src=\"$GIF_ESCOLHIDO\" height=\"160\" style=\"margin-bottom: 10px;\" />|" README.md

      - name: Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md .github/workflows/last_gif_index.txt
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada, não será feito commit."
          else
            git commit -m "Atualizando GIF do README"
            git push
          fi
